# Impostazioni di base del sito
title: "Hi, I'm Lorenzo D'Errico"
description: "Ph.D. Student in Artificial Intelligence @ Federico II"
baseurl: "" # Lascia vuoto se non usi un dominio personalizzato
url: "https://lo3e.github.io" # L'URL del tuo sito

# Tema
theme: jekyll-theme-minimal

# Permalink per link pi√π puliti
permalink: pretty
